### ISSUE TITLE
Notify users concurrently to reduce run time

### ISSUE THREAD

**Issue by WsbTickerBotHandler** [WsbTickerBotHandler/WSB-Ticker-Bot#6]

**Comment by au5ton** [comment]
I'm pretty sure PRAW is designed so that its calls rarely pass rate limits specifically because it _doesn't_ run concurrently and knows all of the timing it needs to do. I could very well be mistaken though.

**Comment by WsbTickerBotHandler** [comment]
You're right, I tried doing what they suggested [here](https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#multiple-threads) and generating multiple Reddit instances but I think each one rate-limits based on headers that are returned from the Reddit API so it won't make the requests faster

From what I've seen the request limit is 1-2 requests per second. This is some log data from the last 12h, still can't tell whether the 3-worker threadpool using different Reddit instances is helping/hurting this time
<img width="270" alt="image" src="https://user-images.githubusercontent.com/66104833/83669236-13867100-a586-11ea-8192-02c43426f6df.png">


The reason I want to parallelize the notification is because AWS Lambda charges by the second. I'd rather make 60 requests in the first 5 seconds of the program then 60 requests spread over a minute.

I tried using threads and some timing code to make sure no more than 60 requests are made per-minute, but which terminates the program at the earliest time possible
https://github.com/WsbTickerBotHandler/WSB-Ticker-Bot/blob/master/src/wsb_reddit.py#L123

**Comment by WsbTickerBotHandler** [comment]
Current idea is to implement this using multiple Reddit accounts (possibly the bot handler's) to work around the hard rate limit.

The main bot lambda will create a list of all notifications needed to be sent to users and push them to an SQS topic. The main lambda (after processing other things) and a helper lambda running different credentials will consume the queue at 60 reqs/minute

**Comment by WsbTickerBotHandler** [comment]
Fixed partially by using SQS to queue batches of 10 notifications and 2 separate consumers consume them and mark each notification as sent. If a batch fails because of timeout, all 10 notifications will be re-added to the queue so there needed to be a check for each sent notification. Still seeing many rate limits from the Reddit side probably related to https://www.reddit.com/r/modnews/comments/hf4tx0/testing_new_rate_limits_for_modmail_and_private/

Age of longest in-flight batch seen around ~5 minutes for large notifications
